stages:
  - build
  - deploy

build:
  image: node:lts
  stage: build
  only:
    - master
  artifacts:
    paths:
      - badges/**
  script:
    - export NPM_VERSION=$(node -e "console.log(require('./package.json').version)")
    - wget -O badges/version.svg https://img.shields.io/badge/version-$NPM_VERSION-blue.svg

deploy:
  image: alshdavid/aws-cli
  stage: deploy
  only:
    - master
  script: 
    - wget https://img.shields.io/badge/version-1.6.0-blue.svg
    - aws s3 rm --recursive s3://alshdavid-public/badges/crayon
    - aws s3 cp --recursive ./badges s3://alshdavid-public/badges/crayon
